# Generated by Django 5.1.3 on 2024-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_testemunho_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Skill')),
                ('classification', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediario'), (3, 'Avancado'), (4, 'Especialista'), (5, 'Master')], default=1)),
            ],
        ),
    ]
