# Generated by Django 5.1.3 on 2024-11-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
